# The workflow for building the stable (regular) version of WinUEFI

name: Build EXE application, installer and disk image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env:
  REPO_PATH: 'D:\a\Windows-Pocket-Edition\Windows-Pocket-Edition'

jobs:
  build_exe:
    name: Build EXE
    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Temporary copy source files
        run: copy "%REPO_PATH%\*" "%REPO_PATH%\build\*"
        shell: cmd

      - name: Build BAT to EXE application
        run: |
          "%REPO_PATH%\bin\bat_to_exe\bat_to_exe.exe" /bat "%REPO_PATH%\os.bat" /exe "%REPO_PATH%\build\Windows-Pocket-Edition-amd64.exe" /x64 /icon "%REPO_PATH%\src\logo.ico" /uac-admin /productversion "${{ env.RELEASE_VERSION }}" /internalname "Windows: Pocket Edition 64-bit"
          "%REPO_PATH%\bin\bat_to_exe\bat_to_exe.exe" /bat "%REPO_PATH%\os.bat" /exe "%REPO_PATH%\build\Windows-Pocket-Edition-i386.exe" /icon "%REPO_PATH%\src\logo.ico" /uac-admin /productversion "${{ env.RELEASE_VERSION }}" /internalname "Windows: Pocket Edition 32-bit"
        shell: cmd
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Pocket-Edition
          path: |
            build/*.exe
            build/*.iso
            build/*.bat
            build/*.ps1
            build/*.py
            build/*.txt
  
  get_file_checksums:
    name: Get file checksums
    needs: [build_exe]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Windows-Pocket-Edition
          path: build/
      
      - name: Generate checksums
        uses: jmgilman/actions-generate-checksum@v1
        with:
          output: build/checksums.txt
          patterns: |
            build/*.exe
            build/*.iso
            build/*.bat
            build/*.ps1
            build/*.py
            build/*.iso
            build/*.img
            build/*.mds
            build/*.dvd
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Pocket-Edition
          path: "build/checksums.txt"
